[package]
name = "deno_json_op"
version = "0.1.0"
authors = ["Elias Sjögreen"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
syn = { version = "1.0", features = [ "full" ] }
